version: '3.8'

service:
  travel-agency-pg:
    image: bitnami/postgresql
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=api-travel-agency
